#!/usr/bin/env python3
"""Write local/REHEARSAL.md (to stdout) from out/rehearsal/: facts.env, the correctness CSVs and the load files.

    python3 local/report.py --sf 1 > local/REHEARSAL.md

Numbers only, no timings. local/rehearsal-notes.md (hand-written after reading the results) is appended.
"""
import argparse
import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LAB = os.path.dirname(HERE)
OUT = os.environ.get("LAB_OUT", os.path.join(LAB, "out", "rehearsal"))
sys.path.insert(0, LAB)
os.environ["LAB_OUT"] = OUT
import compare  # noqa: E402


def facts():
    d = {}
    with open(os.path.join(OUT, "facts.env")) as f:
        for line in f:
            if "=" in line:
                k, v = line.rstrip("\n").split("=", 1)
                d[k] = v
    return d


def kv(path):
    d = {}
    with open(path) as f:
        for line in f:
            if "=" in line:
                k, v = line.rstrip("\n").split("=", 1)
                d[k] = v
    return d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sf", type=int, required=True)
    a = ap.parse_args()
    sf = a.sf
    fx = facts()
    ver = kv(os.path.join(OUT, "P", "pg_clickhouse-version.txt"))
    chv = open(os.path.join(OUT, "P", "clickhouse-version.txt")).read().strip()
    gen = list(csv.DictReader(open(os.path.join(OUT, "datagen-sf%d.csv" % sf))))
    duck = gen[0]["duckdb_version"]
    rows = {r["table"]: int(r["rows"]) for r in gen}
    load = list(csv.DictReader(open(os.path.join(OUT, "P", "load-sf%d.csv" % sf))))
    load_ok = sum(1 for r in load if r["status"] == "ok")

    ref = compare.load("R", sf)
    queries = sorted(ref, key=compare.query_key)
    res = {}
    data = {}
    for t in ("P", "P-s3", "PG"):
        d = compare.load(t, sf)
        if d is not None:
            data[t] = d
            res[t] = {q: compare.verdict(ref.get(q), d.get(q)) for q in queries if q in d}

    def count(t, k):
        return sum(1 for q in res[t] if res[t][q][0] == k)

    gib = lambda b: "%.1f GiB" % (int(b) / 2 ** 30)  # noqa: E731
    o = []
    o.append("# Local rehearsal (SF%d)" % sf)
    o.append("")
    o.append("Measured %s to %s UTC by `local/rehearse.sh --sf %d`. The numbers below are what that run produced; "
             "the file is regenerated by every run (`local/report.py`), the notes at the end are hand-written." %
             (fx["start"], fx["end"], sf))
    o.append("")
    o.append("What this proves: the scripts, the query set and the result comparison work against pg_clickhouse "
             "and PostgreSQL 18 on a laptop. What it does not: anything about Aurora, ClickHouse Cloud, S3, TLS "
             "or timings (none are recorded here).")
    o.append("")
    o.append("## Conditions")
    o.append("")
    o.append("| | |")
    o.append("|---|---|")
    o.append("| Host | %s, %s, %s RAM, %s |" % (fx["host_cpu"], fx["host_arch"], gib(fx["host_mem"]), fx["host_os"]))
    o.append("| Docker VM | %s CPUs, %s |" % (fx["docker_cpus"], gib(fx["docker_mem"])))
    o.append("| Front end image | `%s` |" % fx["pg_image"])
    o.append("| ClickHouse image | `%s` |" % fx["ch_image"])
    o.append("| PostgreSQL | %s |" % ver.get("postgres", "?"))
    o.append("| pg_clickhouse | installed %s, available %s (`pg_available_extensions`), installed after setup %s |" %
             (ver["installed_before"], ver["available"], ver["installed_after"]))
    o.append("| pg_clickhouse.session_settings | `%s` (default, not changed) |" % ver.get("pg_clickhouse.session_settings", "?"))
    o.append("| ClickHouse server | %s (`SELECT version()`); via pg_clickhouse %s |" % (chv, ver.get("clickhouse_server_version", "?")))
    o.append("| DuckDB (generator and R) | CLI %s, Python module %s in `run.py` |" % (duck, compare.duck_version(ref)))
    patches = sorted(f for f in os.listdir(os.path.join(LAB, "patches")) if f.endswith(".diff")) \
        if os.path.isdir(os.path.join(LAB, "patches")) else []
    o.append("| Query set | tpcds-scripts `engines/duckdb/queries`, commit `%s`, %d files; lab patches applied to every target including R: %s |" % (
        compare_sha(), len(queries), ", ".join("`%s`" % f for f in patches) if patches else "none"))
    o.append("| ClickHouse tables | tpcds-scripts `engines/clickhouse/ddl/schema.sql` with the three adaptations of `20-clickhouse-load.sh` (d_date Date32, Nullable where the DDL has no NOT NULL, FixedString as String) |")
    o.append("| Front-end database | `pgc`, binary (`C`) collation (the container default en_US.utf8 is covered in the notes) |")
    o.append("| Plain PostgreSQL | database `plain`, `C` collation, tpcds-scripts `engines/postgres/ddl/schema.sql` (customer.c_last_review_date renamed to c_last_review_date_sk, integer, as dsdgen writes it), default settings, no indexes beyond the DDL's primary keys |")
    o.append("| Data | SF%d by the DuckDB `tpcds` extension, Parquet (zstd), `store_sales` %s rows; loaded into ClickHouse with `file()` instead of `s3()`, no TLS, binary driver on port 9000 |" % (sf, format(rows.get("store_sales", 0), ",")))
    o.append("| Load | %d of %d tables loaded with the row count of `datagen-sf%d.csv` |" % (load_ok, len(load), sf))
    o.append("| Run | concurrency 1, one run per query, per-query timeout %s s (real run: 600 s) |" % fx["timeout"])
    o.append("")
    o.append("## Result vs R (DuckDB)")
    o.append("")
    o.append("Result = rows sorted, numbers to 2 decimals, NULL as `\\N`, sha256 (see `compare.py`).")
    o.append("")
    o.append("| target | match | mismatch | syntax | error | of |")
    o.append("|---|---|---|---|---|---|")
    names = {"P": "P (pg_clickhouse, MergeTree)", "P-s3": "P-s3 (pg_clickhouse, table-function tables; 5 queries)",
             "PG": "PG (plain PostgreSQL 18 over COPY-loaded data)"}
    for t in res:
        o.append("| %s | %d | %d | %d | %d | %d |" % (names[t], count(t, "match"), count(t, "mismatch"),
                                                      count(t, "syntax"), count(t, "error"), len(res[t])))
    for t in res:
        bad = [q for q in queries if q in res[t] and res[t][q][0] != "match"]
        if not bad:
            continue
        o.append("")
        o.append("### %s: not matching (%d)" % (names[t], len(bad)))
        o.append("")
        o.append("| query | verdict | detail |")
        o.append("|---|---|---|")
        for q in bad:
            v, d = res[t][q]
            o.append("| %s | %s | %s |" % (q, v, d.replace("|", "/")))
    for t in ("P", "P-s3"):
        if t not in data:
            continue
        qs = [q for q in queries if q in data[t]]
        full = [q for q in qs if data[t][q].get("pushdown") == "full"]
        part = [q for q in qs if data[t][q].get("pushdown") == "partial"]
        other = [q for q in qs if data[t][q].get("pushdown") not in ("full", "partial")]
        o.append("")
        o.append("## Pushdown, %s (`EXPLAIN (VERBOSE)`: one Foreign Scan and nothing above it = full)" % t)
        o.append("")
        o.append("full %d, partial %d, not classified %d (of %d)." % (len(full), len(part), len(other), len(qs)))
        o.append("")
        o.append("Partial: %s" % (", ".join(part) if part else "none"))
        if other:
            o.append("")
            o.append("Not classified: %s" % ", ".join(other))
    notes = os.path.join(HERE, "rehearsal-notes.md")
    if os.path.isfile(notes):
        o.append("")
        o.append(open(notes).read().rstrip("\n"))
    print("\n".join(o))


def compare_sha():
    # the pinned SHA is defined once, in _lib.sh
    for line in open(os.path.join(LAB, "_lib.sh")):
        if line.startswith("TPCDS_SCRIPTS_SHA="):
            return line.strip().split("=", 1)[1]
    return "?"


if __name__ == "__main__":
    main()
